declare const dbgLog: Logger;
export declare const dbgFileLogger: FileLoggerFactory;
export type LogFn = (file: string, trace: string | string[], ...logs: LogVariableLables) => void;
export type FileLogFn = (trace: string | string[], ...logs: LogVariableLables) => void;
export type StackLogFn = (...logs: LogVariableLables) => void;
export type FileLoggerFactory = (file: string) => FileLogger;
export type StackLoggerFactory = (...trace: string[] | [string | string[]]) => StackLogger;
export type Logger = {
    (file: string, trace: string | string[], ...logs: LogVariableLables): void;
    fileLogger: FileLoggerFactory;
    error: LogFn;
};
export type FileLogger = {
    (trace: string | string[], ...logs: LogVariableLables): void;
    stackLogger: StackLoggerFactory;
    error: FileLogFn;
    file?: string;
};
export type StackLogger = {
    (...logs: LogVariableLables): void;
    stackLoggerInc: StackLoggerFactory;
    error: StackLogFn;
    file: string;
    trace: string | string[];
};
export { dbgLog };
type Label = [label: string, variable: unknown];
type l = Label;
type lx2 = [...l, ...l];
type lx3 = [...l, ...lx2];
type lx4 = [...l, ...lx3];
type lx5 = [...l, ...lx4];
type lx6 = [...l, ...lx5];
type lx7 = [...l, ...lx6];
type lx8 = [...l, ...lx7];
type lx9 = [...l, ...lx8];
type lx10 = [...l, ...lx9];
type lx11 = [...l, ...lx10];
type lx12 = [...l, ...lx11];
type lx13 = [...l, ...lx12];
type lx14 = [...l, ...lx13];
type lx15 = [...l, ...lx14];
type lx16 = [...l, ...lx15];
type lx17 = [...l, ...lx16];
type lx18 = [...l, ...lx17];
type lx19 = [...l, ...lx18];
type lx20 = [...l, ...lx19];
type lx21 = [...l, ...lx20];
type lx22 = [...l, ...lx21];
type lx23 = [...l, ...lx22];
type lx24 = [...l, ...lx23];
type lx25 = [...l, ...lx24];
type lx26 = [...l, ...lx25];
type lx27 = [...l, ...lx26];
type lx28 = [...l, ...lx27];
type lx29 = [...l, ...lx28];
type lx30 = [...l, ...lx29];
type lx31 = [...l, ...lx30];
type lx32 = [...l, ...lx31];
type lx33 = [...l, ...lx32];
type lx34 = [...l, ...lx33];
type lx35 = [...l, ...lx34];
type lx36 = [...l, ...lx35];
type lx37 = [...l, ...lx36];
type lx38 = [...l, ...lx37];
type lx39 = [...l, ...lx38];
type lx40 = [...l, ...lx39];
type lx41 = [...l, ...lx40];
type lx42 = [...l, ...lx41];
type lx43 = [...l, ...lx42];
type lx44 = [...l, ...lx43];
type lx45 = [...l, ...lx44];
type lx46 = [...l, ...lx45];
type lx47 = [...l, ...lx46];
type lx48 = [...l, ...lx47];
type lx49 = [...l, ...lx48];
type lx50 = [...l, ...lx49];
export type LogVariableLables = Label | lx2 | lx3 | lx4 | lx5 | lx6 | lx7 | lx8 | lx9 | lx10 | lx11 | lx12 | lx13 | lx14 | lx15 | lx16 | lx17 | lx18 | lx19 | lx20 | lx21 | lx22 | lx23 | lx24 | lx25 | lx26 | lx27 | lx28 | lx29 | lx30 | lx31 | lx32 | lx33 | lx34 | lx35 | lx36 | lx37 | lx38 | lx39 | lx40 | lx41 | lx42 | lx43 | lx44 | lx45 | lx46 | lx47 | lx48 | lx49 | lx50;
//# sourceMappingURL=logger.d.ts.map