"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const dotenv_1 = __importDefault(require("dotenv"));
console.log(dotenv_1.default.config());
const mongoose_1 = __importDefault(require("mongoose"));
const part_1 = __importDefault(require("./models/part"));
const news_1 = __importDefault(require("./models/news"));
const { MONGODB, REDIS } = process.env;
(async () => {
    if (!MONGODB)
        return console.error(`\n\tFAILED to initialize MongoDB: \"${MONGODB}\"...`);
    await mongoose_1.default.connect(MONGODB);
    console.log(`\n\t> MongoDB: "${MONGODB}" is being initialized...\n`);
    const news = [
        {
            _id: new mongoose_1.default.Types.ObjectId("63584926fbb01a1a8b323ddf"),
            title: "Story 1",
            content: "lorem ipsum 1: the beginnings.",
            createdAt: new Date("2001-01-01T05:00:00.000Z"),
            updatedAt: new Date("2001-01-01T05:00:00.000Z")
        },
        {
            _id: new mongoose_1.default.Types.ObjectId("63584926fbb01a1a8b323de0"),
            title: "Story 2",
            content: "lorem ipsum 2: the reckoning.",
            createdAt: new Date("2002-07-01T04:00:00.000Z"),
            updatedAt: new Date("2002-07-01T04:00:00.000Z")
        },
        {
            _id: new mongoose_1.default.Types.ObjectId("63584926fbb01a1a8b323de1"),
            title: "Story 3",
            content: "lorem ipsum 3: the awakening.",
            createdAt: new Date("2003-03-26T05:00:00.000Z"),
            updatedAt: new Date("2003-03-26T05:00:00.000Z")
        },
        {
            _id: new mongoose_1.default.Types.ObjectId("63584926fbb01a1a8b323de2"),
            title: "Story 4",
            content: "lorem ipsum 4: the reasoning.",
            createdAt: new Date("2004-10-31T04:00:00.000Z"),
            updatedAt: new Date("2004-10-31T04:00:00.000Z")
        },
        {
            _id: new mongoose_1.default.Types.ObjectId("63584926fbb01a1a8b323de3"),
            title: "Story 5",
            content: "lorem ipsum 5: the beckoning.",
            createdAt: new Date("2005-08-14T04:00:00.000Z"),
            updatedAt: new Date("2005-08-14T04:00:00.000Z")
        },
        {
            _id: new mongoose_1.default.Types.ObjectId("63584926fbb01a1a8b323de4"),
            title: "Story 6",
            content: "lorem ipsum 6: the remaking.",
            createdAt: new Date("2006-01-01T05:00:00.000Z"),
            updatedAt: new Date("2006-01-01T05:00:00.000Z")
        },
        {
            _id: new mongoose_1.default.Types.ObjectId("63584926fbb01a1a8b323de5"),
            title: "Story 7",
            content: "lorem ipsum 7: the hampering.",
            createdAt: new Date("2007-01-01T05:00:00.000Z"),
            updatedAt: new Date("2007-01-01T05:00:00.000Z")
        },
        {
            _id: new mongoose_1.default.Types.ObjectId("63584926fbb01a1a8b323de6"),
            title: "Story 8",
            content: "lorem ipsum 8: the foreshadowing.",
            createdAt: new Date("2008-01-01T05:00:00.000Z"),
            updatedAt: new Date("2008-01-01T05:00:00.000Z")
        },
        {
            _id: new mongoose_1.default.Types.ObjectId("63584926fbb01a1a8b323de7"),
            title: "Story 9",
            content: "lorem ipsum 9: the viking.",
            createdAt: new Date("2009-01-01T05:00:00.000Z"),
            updatedAt: new Date("2009-01-01T05:00:00.000Z")
        },
        {
            _id: new mongoose_1.default.Types.ObjectId("63584926fbb01a1a8b323de8"),
            title: "Story 10",
            content: "lorem ipsum 10: the harbinger.",
            createdAt: new Date("2010-10-10T04:00:00.000Z"),
            updatedAt: new Date("2010-10-10T04:00:00.000Z")
        },
        {
            _id: new mongoose_1.default.Types.ObjectId("63584926fbb01a1a8b323de9"),
            title: "Story 11",
            content: "lorem ipsum 11: the jester.",
            createdAt: new Date("2011-10-10T04:00:00.000Z"),
            updatedAt: new Date("2011-10-10T04:00:00.000Z")
        },
        {
            _id: new mongoose_1.default.Types.ObjectId("63584926fbb01a1a8b323dea"),
            title: "Story 12",
            content: "lorem ipsum 12: the conqueror.",
            createdAt: new Date("2012-10-10T04:00:00.000Z"),
            updatedAt: new Date("2012-10-10T04:00:00.000Z")
        }
    ];
    for (const story of news) {
        await news_1.default.updateOne({
            $or: Object.entries(story)
                .filter(([prop]) => ["_id", "title", "content"].includes(prop))
                .map(([p, v]) => ({ [p]: v }))
        }, story, { upsert: true });
    }
    const parts = [
        {
            name: "AMD Ryzen 9 7950X",
            oem: "AMD",
            model: "Ryzen 9 7950X",
            released: new Date("2022-09-27T05:00:00.000Z"),
            MSRP: 699,
            type: "CPU",
            img: "https://c1.neweggimages.com/ProductImageCompressAll300/19-113-771-09.jpg?ex=2",
            typeInfo: {
                platform: "desktop",
                unlocked: true,
                codename: "Raphael",
                architechure: "Zen 4",
                PCIe: "5.0",
                PIB: false,
                socket: "AM5",
                memory: "DDR5",
                memorySpeed: "DDR5-5200",
                memoryChannels: 2,
                cores: 16,
                threads: 32,
                hyperthreading: true,
                SMT: true,
                baseClock: "4.5GHz",
                boostClock: "5.7GHz",
                TjMax: "95C",
                TDP: "170W",
                L1Cache: "1MB",
                L2Cache: "16MB",
                L3Cache: "64MB",
                graphincs: "AMD Radeon Graphics",
                graphincsArchitechure: "RDNA2",
                graphincsCores: 2,
                graphincsBaseClock: "400MHz",
                graphincsBoostClock: "2200MHz",
                processNode: "TSMC 5nm FinFET",
                productFamily: "AMD Ryzen",
                productLine: "AMD Ryzen 9",
                productIdBoxed: "100-100000514WOF",
                productIdTray: "100-100000514"
            }
        },
        {
            name: "AMD Ryzen 9 7900X",
            oem: "AMD",
            model: "Ryzen 9 7900X",
            released: new Date("2022-09-27T05:00:00.000Z"),
            MSRP: 549,
            type: "CPU",
            img: "https://c1.neweggimages.com/ProductImageCompressAll300/19-113-769-02.jpg?ex=2",
            typeInfo: {
                platform: "desktop",
                unlocked: true,
                codename: "Raphael",
                architechure: "Zen 4",
                PCIe: "5.0",
                PIB: false,
                socket: "AM5",
                memory: "DDR5",
                memorySpeed: "DDR5-5200",
                memoryChannels: 2,
                cores: 12,
                threads: 24,
                hyperthreading: true,
                SMT: true,
                baseClock: "4.7GHz",
                boostClock: "5.6GHz",
                TjMax: "95C",
                TDP: "170W",
                L1Cache: "768KB",
                L2Cache: "12MB",
                L3Cache: "64MB",
                graphincs: "AMD Radeon Graphics",
                graphincsArchitechure: "RDNA2",
                graphincsCores: 2,
                graphincsBaseClock: "400MHz",
                graphincsBoostClock: "2200MHz",
                processNode: "TSMC 5nm FinFET",
                productFamily: "AMD Ryzen",
                productLine: "AMD Ryzen 9",
                productIdBoxed: "100-100000589WOF",
                productIdTray: "100-100000589"
            }
        },
        {
            name: "AMD Ryzen 7 7700X",
            oem: "AMD",
            model: "Ryzen 7 7700X",
            released: new Date("2022-09-27T05:00:00.000Z"),
            MSRP: 399,
            type: "CPU",
            img: "https://c1.neweggimages.com/ProductImageCompressAll300/19-113-768-01.jpg?ex=2",
            typeInfo: {
                platform: "desktop",
                unlocked: true,
                codename: "Raphael",
                architechure: "Zen 4",
                PCIe: "5.0",
                PIB: false,
                socket: "AM5",
                memory: "DDR5",
                memorySpeed: "DDR5-5200",
                memoryChannels: 2,
                cores: 8,
                threads: 16,
                hyperthreading: true,
                SMT: true,
                baseClock: "4.5GHz",
                boostClock: "5.4GHz",
                TjMax: "95C",
                TDP: "105W",
                L1Cache: "512KB",
                L2Cache: "8MB",
                L3Cache: "32MB",
                graphincs: "AMD Radeon Graphics",
                graphincsArchitechure: "RDNA2",
                graphincsCores: 2,
                graphincsBaseClock: "400MHz",
                graphincsBoostClock: "2200MHz",
                processNode: "TSMC 5nm FinFET",
                productFamily: "AMD Ryzen",
                productLine: "AMD Ryzen 7",
                productIdBoxed: "100-100000591WOF",
                productIdTray: "100-100000591"
            }
        },
        {
            name: "AMD Ryzen 5 7600X",
            oem: "AMD",
            model: "Ryzen 5 7600X",
            released: new Date("2022-09-27T05:00:00.000Z"),
            MSRP: 299,
            type: "CPU",
            img: "https://c1.neweggimages.com/ProductImageCompressAll300/19-113-770-02.jpg?ex=2",
            typeInfo: {
                platform: "desktop",
                unlocked: true,
                codename: "Raphael",
                architechure: "Zen 4",
                PIB: false,
                PCIe: "5.0",
                socket: "AM5",
                memory: "DDR5",
                memorySpeed: "DDR5-5200",
                memoryChannels: 2,
                cores: 6,
                threads: 12,
                hyperthreading: true,
                SMT: true,
                baseClock: "4.7GHz",
                boostClock: "5.3GHz",
                TjMax: "95C",
                TDP: "105W",
                L1Cache: "384KB",
                L2Cache: "6MB",
                L3Cache: "32MB",
                graphincs: "AMD Radeon Graphics",
                graphincsArchitechure: "RDNA2",
                graphincsCores: 2,
                graphincsBaseClock: "400MHz",
                graphincsBoostClock: "2200MHz",
                processNode: "TSMC 5nm FinFET",
                productFamily: "AMD Ryzen",
                productLine: "AMD Ryzen 5",
                productIdBoxed: "100-100000593WOF",
                productIdTray: "100-100000593"
            }
        },
        {
            name: "AMD Ryzen 9 5950X",
            oem: "AMD",
            model: "Ryzen 9 5950X",
            released: new Date("2020-11-05T05:00:00.000Z"),
            MSRP: 799,
            type: "CPU",
            img: "https://c1.neweggimages.com/ProductImageCompressAll300/19-113-663-V01.jpg?ex=2",
            typeInfo: {
                platform: "desktop",
                unlocked: true,
                codename: "Vermeer",
                architechure: "Zen 3",
                PIB: false,
                PCIe: "4.0",
                socket: "AM4",
                memory: "DDR4",
                memorySpeed: "DDR4-3200",
                memoryChannels: 2,
                cores: 16,
                threads: 32,
                hyperthreading: true,
                SMT: true,
                baseClock: "3.4GHz",
                boostClock: "4.95GHz",
                TjMax: "90C",
                TDP: "105W",
                L1Cache: "1MB",
                L2Cache: "8MB",
                L3Cache: "64MB",
                graphics: false,
                processNode: "TSMC 7nm FinFET",
                productFamily: "AMD Ryzen",
                productLine: "AMD Ryzen 9",
                productIdBoxed: "100-100000059WOF",
                productIdTray: "100-000000059"
            }
        },
        {
            _id: new mongoose_1.default.Types.ObjectId("635326960db6d88a90c6b5a5"),
            name: "AMD Ryzen 9 5900X",
            oem: "AMD",
            model: "Ryzen 9 5900X",
            released: new Date("2020-11-05T05:00:00.000Z"),
            MSRP: 549,
            type: "CPU",
            img: "https://c1.neweggimages.com/ProductImageCompressAll300/19-113-664-V01.jpg?ex=2",
            typeInfo: {
                platform: "desktop",
                unlocked: true,
                codename: "Vermeer",
                architechure: "Zen 3",
                PIB: false,
                PCIe: "4.0",
                socket: "AM4",
                memory: "DDR4",
                memorySpeed: "DDR4-3200",
                memoryChannels: 2,
                cores: 12,
                threads: 24,
                hyperthreading: true,
                SMT: true,
                baseClock: "3.7GHz",
                boostClock: "4.8GHz",
                TjMax: "90C",
                TDP: "105W",
                L1Cache: "768KB",
                L2Cache: "6MB",
                L3Cache: "64MB",
                graphics: false,
                processNode: "TSMC 7nm FinFET",
                productFamily: "AMD Ryzen",
                productLine: "AMD Ryzen 9",
                productIdBoxed: "100-100000061WOF",
                productIdTray: "100-000000061"
            }
        },
        {
            _id: new mongoose_1.default.Types.ObjectId("635326960db6d88a90c6b5a6"),
            name: "AMD Ryzen 7 5800X3D",
            oem: "AMD",
            model: "Ryzen 7 5800X3D",
            released: new Date("2022-04-20T04:00:00.000Z"),
            MSRP: 449,
            type: "CPU",
            img: "https://c1.neweggimages.com/ProductImageCompressAll300/19-113-734-S04.jpg?ex=2",
            typeInfo: {
                platform: "desktop",
                unlocked: true,
                codename: "Vermeer",
                architechure: "Zen 3",
                PIB: false,
                PCIe: "4.0",
                socket: "AM4",
                memory: "DDR4",
                memorySpeed: "DDR4-3200",
                memoryChannels: 2,
                cores: 8,
                threads: 16,
                hyperthreading: true,
                SMT: true,
                baseClock: "3.4GHz",
                boostClock: "4.5GHz",
                TjMax: "90C",
                TDP: "105W",
                L1Cache: "512KB",
                L2Cache: "4MB",
                L3Cache: "96MB",
                graphics: false,
                processNode: "TSMC 7nm FinFET",
                productFamily: "AMD Ryzen",
                productLine: "AMD Ryzen 7",
                productIdBoxed: "100-100000651WOF",
                productIdTray: "100-000000651"
            }
        },
        {
            _id: new mongoose_1.default.Types.ObjectId("635326960db6d88a90c6b5a7"),
            name: "AMD Ryzen 7 5800X",
            oem: "AMD",
            model: "Ryzen 7 5800X",
            released: new Date("2020-11-05T05:00:00.000Z"),
            MSRP: 449,
            type: "CPU",
            img: "https://c1.neweggimages.com/ProductImageCompressAll300/19-113-665-V01.jpg?ex=2",
            typeInfo: {
                platform: "desktop",
                unlocked: true,
                codename: "Vermeer",
                architechure: "Zen 3",
                PIB: false,
                PCIe: "4.0",
                socket: "AM4",
                memory: "DDR4",
                memorySpeed: "DDR4-3200",
                memoryChannels: 2,
                cores: 8,
                threads: 16,
                hyperthreading: true,
                SMT: true,
                baseClock: "3.8GHz",
                boostClock: "4.7GHz",
                TjMax: "90C",
                TDP: "105W",
                L1Cache: "512KB",
                L2Cache: "4MB",
                L3Cache: "32MB",
                graphics: false,
                processNode: "TSMC 7nm FinFET",
                productFamily: "AMD Ryzen",
                productLine: "AMD Ryzen 7",
                productIdBoxed: "100-100000063WOF",
                productIdTray: "100-000000063"
            }
        },
        {
            _id: new mongoose_1.default.Types.ObjectId("635326960db6d88a90c6b5a8"),
            name: "AMD Ryzen 7 5700X",
            oem: "AMD",
            model: "Ryzen 7 5700X",
            released: new Date("2022-04-04T04:00:00.000Z"),
            MSRP: 299,
            type: "CPU",
            img: "https://c1.neweggimages.com/ProductImageCompressAll300/19-113-735-V01.jpg?ex=2",
            typeInfo: {
                platform: "desktop",
                unlocked: true,
                codename: "Vermeer",
                architechure: "Zen 3",
                PIB: false,
                PCIe: "4.0",
                socket: "AM4",
                memory: "DDR4",
                memorySpeed: "DDR4-3200",
                memoryChannels: 2,
                cores: 8,
                threads: 16,
                hyperthreading: true,
                SMT: true,
                baseClock: "3.4GHz",
                boostClock: "4.6GHz",
                TjMax: "90C",
                TDP: "65W",
                L1Cache: "512KB",
                L2Cache: "4MB",
                L3Cache: "32MB",
                graphics: false,
                processNode: "TSMC 7nm FinFET",
                productFamily: "AMD Ryzen",
                productLine: "AMD Ryzen 7",
                productIdBoxed: "100-100000926WOF",
                productIdTray: "100-000000926"
            }
        },
        {
            name: "AMD Ryzen 7 5700G",
            oem: "AMD",
            model: "Ryzen 7 5700G",
            released: new Date("2021-08-05T04:00:00.000Z"),
            MSRP: 359,
            type: "CPU",
            img: "https://c1.neweggimages.com/ProductImageCompressAll300/19-113-682-V01.jpg?ex=2",
            typeInfo: {
                platform: "desktop",
                unlocked: true,
                codename: "Cezanne",
                architechure: "Zen 3",
                PIB: "Wraith Stealth",
                PCIe: "3.0",
                socket: "AM4",
                memory: "DDR4",
                memorySpeed: "DDR4-3200",
                memoryChannels: 2,
                cores: 8,
                threads: 16,
                hyperthreading: true,
                SMT: true,
                baseClock: "3.8GHz",
                boostClock: "4.6GHz",
                TjMax: "95C",
                TDP: "65W",
                L1Cache: "512KB",
                L2Cache: "4MB",
                L3Cache: "16MB",
                graphics: "AMD Radeon Graphics",
                graphincsArchitechure: "GCN5 Vega",
                graphincsCores: 8,
                graphincsBoostClock: "2000MHz",
                processNode: "TSMC 7nm FinFET",
                productFamily: "AMD Ryzen",
                productLine: "AMD Ryzen 7 5000 G-series Desktop Processors with Radeon Graphics",
                productIdBoxed: "100-100000263BOX",
                productIdTray: "100-000000263"
            }
        },
        {
            _id: new mongoose_1.default.Types.ObjectId("635326960db6d88a90c6b5a9"),
            name: "AMD Ryzen 5 5600X",
            oem: "AMD",
            model: "Ryzen 5 5600X",
            released: new Date("2020-11-05T05:00:00.000Z"),
            MSRP: 299,
            type: "CPU",
            img: "https://c1.neweggimages.com/ProductImageCompressAll300/19-113-666-V01.jpg?ex=2",
            typeInfo: {
                platform: "desktop",
                unlocked: true,
                codename: "Vermeer",
                architechure: "Zen 3",
                PIB: "Wraith Stealth",
                PCIe: "4.0",
                socket: "AM4",
                memory: "DDR4",
                memorySpeed: "DDR4-3200",
                memoryChannels: 2,
                cores: 6,
                threads: 12,
                hyperthreading: true,
                SMT: true,
                baseClock: "3.7GHz",
                boostClock: "4.6GHz",
                TjMax: "95C",
                TDP: "65W",
                L1Cache: "384KB",
                L2Cache: "3MB",
                L3Cache: "32MB",
                graphics: false,
                processNode: "TSMC 7nm FinFET",
                productFamily: "AMD Ryzen",
                productLine: "AMD Ryzen 5",
                productIdBoxed: "100-100000065BOX",
                productIdTray: "100-000000065"
            }
        },
        {
            _id: new mongoose_1.default.Types.ObjectId("635326960db6d88a90c6b5aa"),
            name: "AMD Ryzen 5 5600",
            oem: "AMD",
            model: "Ryzen 5 5600",
            released: new Date("2022-04-04T04:00:00.000Z"),
            MSRP: 199,
            type: "CPU",
            img: "https://c1.neweggimages.com/ProductImageCompressAll300/19-113-736-V03.jpg?ex=2",
            typeInfo: {
                platform: "desktop",
                unlocked: true,
                codename: "Vermeer",
                architechure: "Zen 3",
                PIB: "Wraith Stealth",
                PCIe: "4.0",
                socket: "AM4",
                memory: "DDR4",
                memorySpeed: "DDR4-3200",
                memoryChannels: 2,
                cores: 6,
                threads: 12,
                hyperthreading: true,
                SMT: true,
                baseClock: "3.5GHz",
                boostClock: "4.4GHz",
                TjMax: "90C",
                TDP: "65W",
                L1Cache: "384KB",
                L2Cache: "3MB",
                L3Cache: "32MB",
                graphics: false,
                processNode: "TSMC 7nm FinFET",
                productFamily: "AMD Ryzen",
                productLine: "AMD Ryzen 5",
                productIdBoxed: "100-100000927BOX",
                productIdTray: "100-000000927"
            }
        },
        {
            name: "AMD Ryzen 5 5600G",
            oem: "AMD",
            model: "Ryzen 5 5600G",
            released: new Date("2021-08-05T04:00:00.000Z"),
            MSRP: 259,
            type: "CPU",
            img: "https://c1.neweggimages.com/ProductImageCompressAll300/19-113-683-V01.jpg?ex=2",
            typeInfo: {
                platform: "desktop",
                unlocked: true,
                codename: "Cezanne",
                architechure: "Zen 3",
                PIB: "Wraith Stealth",
                PCIe: "3.0",
                socket: "AM4",
                memory: "DDR4",
                memorySpeed: "DDR4-3200",
                memoryChannels: 2,
                cores: 6,
                threads: 12,
                hyperthreading: true,
                SMT: true,
                baseClock: "3.9GHz",
                boostClock: "4.4GHz",
                TjMax: "95C",
                TDP: "65W",
                L1Cache: "384KB",
                L2Cache: "3MB",
                L3Cache: "16MB",
                graphics: "AMD Radeon Graphics",
                graphincsArchitechure: "GCN5 Vega",
                graphincsCores: 7,
                graphincsBoostClock: "1900MHz",
                processNode: "TSMC 7nm FinFET",
                productFamily: "AMD Ryzen",
                productLine: "AMD Ryzen 5 5000 G-series Desktop Processors with Radeon Graphics",
                productIdBoxed: "100-100000252BOX",
                productIdTray: "100-000000252"
            }
        },
        {
            _id: new mongoose_1.default.Types.ObjectId("635326960db6d88a90c6b5ab"),
            name: "AMD Ryzen 5 5500",
            oem: "AMD",
            model: "Ryzen 5 5500",
            released: new Date("2022-04-04T04:00:00.000Z"),
            MSRP: 159,
            type: "CPU",
            img: "https://c1.neweggimages.com/ProductImageCompressAll300/19-113-737-V03.jpg?ex=2",
            typeInfo: {
                platform: "desktop",
                unlocked: true,
                codename: "Cezanne",
                architechure: "Zen 3",
                PIB: "Wraith Stealth",
                PCIe: "3.0",
                socket: "AM4",
                memory: "DDR4",
                memorySpeed: "DDR4-3200",
                memoryChannels: 2,
                cores: 6,
                threads: 12,
                hyperthreading: true,
                SMT: true,
                baseClock: "3.6GHz",
                boostClock: "4.2GHz",
                TjMax: "90C",
                TDP: "65W",
                L1Cache: "384KB",
                L2Cache: "3MB",
                L3Cache: "16MB",
                graphics: false,
                processNode: "TSMC 7nm FinFET",
                productFamily: "AMD Ryzen",
                productLine: "AMD Ryzen 5 5000",
                productIdBoxed: "100-100000457BOX",
                productIdTray: "100-000000457"
            }
        },
        {
            name: "AMD Ryzen 5 4600G",
            oem: "AMD",
            model: "Ryzen 5 4600G",
            released: new Date("2022-04-04T04:00:00.000Z"),
            MSRP: 154,
            type: "CPU",
            img: "https://i5.walmartimages.com/asr/253aadbc-fff8-4f84-8240-844a57dcf544.e95f5ab7747f8520710a42193d303a56.jpeg",
            typeInfo: {
                platform: "desktop",
                unlocked: true,
                codename: "Renoir",
                architechure: "Zen 2",
                PIB: "Wraith Stealth",
                PCIe: "3.0",
                socket: "AM4",
                memory: "DDR4",
                memorySpeed: "DDR4-3200",
                memoryChannels: 2,
                cores: 6,
                threads: 12,
                hyperthreading: true,
                SMT: true,
                baseClock: "3.7GHz",
                boostClock: "4.2GHz",
                TjMax: "95C",
                TDP: "65W",
                L1Cache: "384KB",
                L2Cache: "3MB",
                L3Cache: "8MB",
                graphics: "AMD Radeon Graphics",
                graphincsArchitechure: "GCN5 Vega",
                graphincsCores: 7,
                graphincsBoostClock: "1900MHz",
                processNode: "TSMC 7nm FinFET",
                productFamily: "AMD Ryzen",
                productLine: "AMD Ryzen 5 4000 G-series Desktop Processors with Radeon Graphics",
                productIdBoxed: "100-100000147BOX",
                productIdTray: "100-000000147"
            }
        },
        {
            name: "AMD Ryzen 5 4500",
            oem: "AMD",
            model: "Ryzen 5 4500",
            released: new Date("2022-04-04T04:00:00.000Z"),
            MSRP: 129,
            type: "CPU",
            img: "https://c1.neweggimages.com/ProductImage/APRGS2205040HDDWL1B.jpg",
            typeInfo: {
                platform: "desktop",
                unlocked: true,
                codename: "Renoir",
                architechure: "Zen 2",
                PIB: "Wraith Stealth",
                PCIe: "3.0",
                socket: "AM4",
                memory: "DDR4",
                memorySpeed: "DDR4-3200",
                memoryChannels: 2,
                cores: 6,
                threads: 12,
                hyperthreading: true,
                SMT: true,
                baseClock: "3.6GHz",
                boostClock: "4.1GHz",
                TjMax: "95C",
                TDP: "65W",
                L1Cache: "384KB",
                L2Cache: "3MB",
                L3Cache: "8MB",
                graphics: false,
                processNode: "TSMC 7nm FinFET",
                productFamily: "AMD Ryzen",
                productLine: "AMD Ryzen 5",
                productIdBoxed: "100-100000644BOX",
                productIdTray: "100-000000644"
            }
        },
        {
            name: "AMD Ryzen 5 4100",
            oem: "AMD",
            model: "Ryzen 5 4100",
            released: new Date("2022-04-04T04:00:00.000Z"),
            MSRP: 99,
            type: "CPU",
            img: "https://c1.neweggimages.com/ProductImageCompressAll300/APRGS220504H6qmG.jpg?ex=2",
            typeInfo: {
                platform: "desktop",
                unlocked: true,
                codename: "Renoir",
                architechure: "Zen 2",
                PIB: "Wraith Stealth",
                PCIe: "3.0",
                socket: "AM4",
                memory: "DDR4",
                memorySpeed: "DDR4-3200",
                memoryChannels: 2,
                cores: 4,
                threads: 8,
                hyperthreading: true,
                SMT: true,
                baseClock: "3.8GHz",
                boostClock: "4.0GHz",
                TjMax: "95C",
                TDP: "65W",
                L1Cache: "256KB",
                L2Cache: "2MB",
                L3Cache: "4MB",
                graphics: false,
                processNode: "TSMC 7nm FinFET",
                productFamily: "AMD Ryzen",
                productLine: "AMD Ryzen 3",
                productIdBoxed: "100-100000510BOX",
                productIdTray: "100-000000510"
            }
        },
        {
            name: "Intel Core i9-13900K",
            oem: "Intel",
            model: "Core i9-13900K",
            released: new Date("2022-10-20T05:00:00.000Z"),
            MSRP: 589,
            type: "CPU",
            img: "https://c1.neweggimages.com/ProductImageCompressAll300/19-118-412-V01.jpg?ex=2",
            typeInfo: {
                platform: "desktop",
                unlocked: true,
                codename: "Raptor Lake",
                architechure: "Raptor Cove / Gracemont",
                PIB: false,
                PCIe: "5.0",
                socket: "FCLGA1700",
                memory: "DDR5 / DDR4",
                memorySpeed: "DDR5-5600 / DDR4-3200",
                memoryChannels: 2,
                cores: 24,
                pCores: 8,
                eCores: 16,
                threads: 32,
                hyperthreading: true,
                SMT: true,
                baseClock: "3.0GHz (p-core) / 2.2GHz (e-core)",
                boostClock: "5.8GHz (p-core) / 4.3GHz (e-core)",
                TjMax: "100C",
                TDP: "125W",
                L1Cache: "80KB",
                L2Cache: "32MB",
                L3Cache: "36MB",
                graphics: "Intel UHD Graphics 770",
                graphincsArchitechure: "Xe",
                graphincsCores: "32",
                graphincsBaseClock: "300MHz",
                graphincsBoostClock: "1.65GHz",
                processNode: "Intel 7",
                productFamily: "Intel Core",
                productLine: "Intel Core i9",
                productIdBoxed: "BX8071513900K",
                productIdTray: "BX8071513900K"
            }
        },
        {
            name: "Intel Core i9-13900KF",
            oem: "Intel",
            model: "Core i9-13900KF",
            released: new Date("2022-10-20T05:00:00.000Z"),
            MSRP: 564,
            type: "CPU",
            img: "https://c1.neweggimages.com/ProductImageCompressAll300/19-118-412-V01.jpg?ex=2",
            typeInfo: {
                platform: "desktop",
                unlocked: true,
                codename: "Raptor Lake",
                architechure: "Raptor Cove / Gracemont",
                PIB: false,
                PCIe: "5.0",
                socket: "FCLGA1700",
                memory: "DDR5 / DDR4",
                memorySpeed: "DDR5-5600 / DDR4-3200",
                memoryChannels: 2,
                cores: 24,
                pCores: 8,
                eCores: 16,
                threads: 32,
                hyperthreading: true,
                SMT: true,
                baseClock: "3.0GHz (p-core) / 2.2GHz (e-core)",
                boostClock: "5.8GHz (p-core) / 4.3GHz (e-core)",
                TjMax: "100C",
                TDP: "125W",
                L1Cache: "80KB",
                L2Cache: "32MB",
                L3Cache: "36MB",
                graphics: false,
                processNode: "Intel 7",
                productFamily: "Intel Core",
                productLine: "Intel Core i9",
                productIdBoxed: "BX8071513900KF",
                productIdTray: "BX8071513900KF"
            }
        },
        {
            name: "Intel Core i7-13700K",
            oem: "Intel",
            model: "Core i7-13700K",
            released: new Date("2022-10-20T05:00:00.000Z"),
            MSRP: 409,
            type: "CPU",
            img: "https://c1.neweggimages.com/ProductImageCompressAll300/19-118-412-V01.jpg?ex=2",
            typeInfo: {
                platform: "desktop",
                unlocked: true,
                codename: "Raptor Lake",
                architechure: "Raptor Cove / Gracemont",
                PIB: false,
                PCIe: "5.0",
                socket: "FCLGA1700",
                memory: "DDR5 / DDR4",
                memorySpeed: "DDR5-5600 / DDR4-3200",
                memoryChannels: 2,
                cores: 16,
                pCores: 8,
                eCores: 8,
                threads: 24,
                hyperthreading: true,
                SMT: true,
                baseClock: "3.4GHz (p-core) / 2.5GHz (e-core)",
                boostClock: "5.3GHz (p-core) / 4.2GHz (e-core)",
                TjMax: "100C",
                TDP: "125W",
                L1Cache: "80KB",
                L2Cache: "24MB",
                L3Cache: "30MB",
                graphics: "Intel UHD Graphics 770",
                graphincsArchitechure: "Xe",
                graphincsCores: "32",
                graphincsBaseClock: "300MHz",
                graphincsBoostClock: "1.6GHz",
                processNode: "Intel 7",
                productFamily: "Intel Core",
                productLine: "Intel Core i7",
                productIdBoxed: "BX8071513700K",
                productIdTray: "BX8071513700K"
            }
        },
        {
            name: "Intel Core i7-13700KF",
            oem: "Intel",
            model: "Core i7-13700KF",
            released: new Date("2022-10-20T05:00:00.000Z"),
            MSRP: 384,
            type: "CPU",
            img: "https://c1.neweggimages.com/ProductImageCompressAll300/19-118-412-V01.jpg?ex=2",
            typeInfo: {
                platform: "desktop",
                unlocked: true,
                codename: "Raptor Lake",
                architechure: "Raptor Cove / Gracemont",
                PIB: false,
                PCIe: "5.0",
                socket: "FCLGA1700",
                memory: "DDR5 / DDR4",
                memorySpeed: "DDR5-5600 / DDR4-3200",
                memoryChannels: 2,
                cores: 16,
                pCores: 8,
                eCores: 8,
                threads: 24,
                hyperthreading: true,
                SMT: true,
                baseClock: "3.4GHz (p-core) / 2.5GHz (e-core)",
                boostClock: "5.3GHz (p-core) / 4.2GHz (e-core)",
                TjMax: "100C",
                TDP: "125W",
                L1Cache: "80KB",
                L2Cache: "24MB",
                L3Cache: "30MB",
                graphics: false,
                processNode: "Intel 7",
                productFamily: "Intel Core",
                productLine: "Intel Core i7",
                productIdBoxed: "BX8071513700KF",
                productIdTray: "BX8071513700KF"
            }
        },
        {
            name: "Intel Core i5-13600K",
            oem: "Intel",
            model: "Core i5-13600K",
            released: new Date("2022-10-20T05:00:00.000Z"),
            MSRP: 319,
            type: "CPU",
            img: "https://c1.neweggimages.com/ProductImageCompressAll300/19-118-412-V01.jpg?ex=2",
            typeInfo: {
                platform: "desktop",
                unlocked: true,
                codename: "Raptor Lake",
                architechure: "Raptor Cove / Gracemont",
                PIB: false,
                PCIe: "5.0",
                socket: "FCLGA1700",
                memory: "DDR5 / DDR4",
                memorySpeed: "DDR5-5600 / DDR4-3200",
                memoryChannels: 2,
                cores: 14,
                pCores: 6,
                eCores: 8,
                threads: 20,
                hyperthreading: true,
                SMT: true,
                baseClock: "3.5GHz (p-core) / 2.6GHz (e-core)",
                boostClock: "5.1GHz (p-core) / 3.9GHz (e-core)",
                TjMax: "100C",
                TDP: "125W",
                L1Cache: "80KB",
                L2Cache: "20MB",
                L3Cache: "24MB",
                graphics: "Intel UHD Graphics 770",
                graphincsArchitechure: "Xe",
                graphincsCores: "32",
                graphincsBaseClock: "300MHz",
                graphincsBoostClock: "1.5GHz",
                processNode: "Intel 7",
                productFamily: "Intel Core",
                productLine: "Intel Core i5",
                productIdBoxed: "BX8071513600K",
                productIdTray: "BX8071513600K"
            }
        },
        {
            name: "Intel Core i5-13600KF",
            oem: "Intel",
            model: "Core i5-13600KF",
            released: new Date("2022-10-20T05:00:00.000Z"),
            MSRP: 294,
            type: "CPU",
            img: "https://c1.neweggimages.com/ProductImageCompressAll300/19-118-412-V01.jpg?ex=2",
            typeInfo: {
                platform: "desktop",
                unlocked: true,
                codename: "Raptor Lake",
                architechure: "Raptor Cove / Gracemont",
                PIB: false,
                PCIe: "5.0",
                socket: "FCLGA1700",
                memory: "DDR5 / DDR4",
                memorySpeed: "DDR5-5600 / DDR4-3200",
                memoryChannels: 2,
                cores: 14,
                pCores: 6,
                eCores: 8,
                threads: 20,
                hyperthreading: true,
                SMT: true,
                baseClock: "3.5GHz (p-core) / 2.6GHz (e-core)",
                boostClock: "5.1GHz (p-core) / 3.9GHz (e-core)",
                TjMax: "100C",
                TDP: "125W",
                L1Cache: "80KB",
                L2Cache: "20MB",
                L3Cache: "24MB",
                graphics: false,
                processNode: "Intel 7",
                productFamily: "Intel Core",
                productLine: "Intel Core i5",
                productIdBoxed: "BX8071513600KF",
                productIdTray: "BX8071513600KF"
            }
        },
        {
            name: "Intel Core i9-12900KS",
            oem: "Intel",
            model: "Core i9-12900KS",
            released: new Date("2022-04-05T05:00:00.000Z"),
            MSRP: 813,
            type: "CPU",
            img: "https://c1.neweggimages.com/ProductImageCompressAll300/19-118-392-V07.jpg?ex=2",
            typeInfo: {
                platform: "desktop",
                unlocked: true,
                codename: "Alder Lake",
                architechure: "Golden Cove / Gracemont",
                PIB: false,
                PCIe: "5.0",
                socket: "FCLGA1700",
                memory: "DDR5 / DDR4",
                memorySpeed: "DDR5-4800 / DDR4-3200",
                memoryChannels: 2,
                cores: 16,
                pCores: 8,
                eCores: 8,
                threads: 24,
                hyperthreading: true,
                SMT: true,
                baseClock: "3.4GHz (p-core) / 2.5GHz (e-core)",
                boostClock: "5.5GHz (p-core) / 4.0GHz (e-core)",
                TjMax: "90C",
                TDP: "150W",
                L1Cache: "80KB",
                L2Cache: "14MB",
                L3Cache: "30MB",
                graphics: "Intel UHD Graphics 770",
                graphincsArchitechure: "Xe",
                graphincsCores: "32",
                graphincsBaseClock: "300MHz",
                graphincsBoostClock: "1.55GHz",
                processNode: "Intel 7",
                productFamily: "Intel Core",
                productLine: "Intel Core i9",
                productIdBoxed: "BX8071512900KS",
                productIdTray: "BX8071512900KS"
            }
        },
        {
            name: "Intel Core i9-12900K",
            oem: "Intel",
            model: "Core i9-12900K",
            released: new Date("2021-11-04T05:00:00.000Z"),
            MSRP: 648,
            type: "CPU",
            img: "https://c1.neweggimages.com/ProductImageCompressAll300/19-118-339-05.jpg?ex=2",
            typeInfo: {
                platform: "desktop",
                unlocked: true,
                codename: "Alder Lake",
                architechure: "Golden Cove / Gracemont",
                PIB: false,
                PCIe: "5.0",
                socket: "FCLGA1700",
                memory: "DDR5 / DDR4",
                memorySpeed: "DDR5-4800 / DDR4-3200",
                memoryChannels: 2,
                cores: 16,
                pCores: 8,
                eCores: 8,
                threads: 24,
                hyperthreading: true,
                SMT: true,
                baseClock: "3.2GHz (p-core) / 2.4GHz (e-core)",
                boostClock: "5.2GHz (p-core) / 3.9GHz (e-core)",
                TjMax: "100C",
                TDP: "125W",
                L1Cache: "80KB",
                L2Cache: "14MB",
                L3Cache: "30MB",
                graphics: "Intel UHD Graphics 770",
                graphincsArchitechure: "Xe",
                graphincsCores: "32",
                graphincsBaseClock: "300MHz",
                graphincsBoostClock: "1.5GHz",
                processNode: "Intel 7",
                productFamily: "Intel Core",
                productLine: "Intel Core i9",
                productIdBoxed: "BX8071512900K",
                productIdTray: "BX8071512900K"
            }
        },
        {
            name: "Intel Core i9-12900KF",
            oem: "Intel",
            model: "Core i9-12900KF",
            released: new Date("2021-11-04T05:00:00.000Z"),
            MSRP: 620,
            type: "CPU",
            img: "https://c1.neweggimages.com/ProductImageCompressAll300/19-118-341-06.jpg?ex=2",
            typeInfo: {
                platform: "desktop",
                unlocked: true,
                codename: "Alder Lake",
                architechure: "Golden Cove / Gracemont",
                PIB: false,
                PCIe: "5.0",
                socket: "FCLGA1700",
                memory: "DDR5 / DDR4",
                memorySpeed: "DDR5-4800 / DDR4-3200",
                memoryChannels: 2,
                cores: 16,
                pCores: 8,
                eCores: 8,
                threads: 24,
                hyperthreading: true,
                SMT: true,
                baseClock: "3.2GHz (p-core) / 2.4GHz (e-core)",
                boostClock: "5.2GHz (p-core) / 3.9GHz (e-core)",
                TjMax: "100C",
                TDP: "125W",
                L1Cache: "80KB",
                L2Cache: "14MB",
                L3Cache: "30MB",
                graphics: false,
                processNode: "Intel 7",
                productFamily: "Intel Core",
                productLine: "Intel Core i9",
                productIdBoxed: "BX8071512900KF",
                productIdTray: "BX8071512900KF"
            }
        },
        {
            name: "Intel Core i9-12900",
            oem: "Intel",
            model: "Core i9-12900",
            released: new Date("2022-01-01T05:00:00.000Z"),
            MSRP: 538,
            type: "CPU",
            img: "https://c1.neweggimages.com/ProductImageCompressAll300/A24GD2203110EQRUQC1.jpg?ex=2",
            typeInfo: {
                platform: "desktop",
                unlocked: false,
                codename: "Alder Lake",
                architechure: "Golden Cove / Gracemont",
                PIB: "Intel Laminar RM1",
                PCIe: "5.0",
                socket: "FCLGA1700",
                memory: "DDR5 / DDR4",
                memorySpeed: "DDR5-4800 / DDR4-3200",
                memoryChannels: 2,
                cores: 16,
                pCores: 8,
                eCores: 8,
                threads: 24,
                hyperthreading: true,
                SMT: true,
                baseClock: "2.4GHz (p-core) / 1.8GHz (e-core)",
                boostClock: "5.1GHz (p-core) / 3.8GHz (e-core)",
                TjMax: "100C",
                TDP: "65W",
                L1Cache: "80KB",
                L2Cache: "14MB",
                L3Cache: "30MB",
                graphics: "Intel UHD Graphics 770",
                graphincsArchitechure: "Xe",
                graphincsCores: "32",
                graphincsBaseClock: "300MHz",
                graphincsBoostClock: "1.55GHz",
                processNode: "Intel 7",
                productFamily: "Intel Core",
                productLine: "Intel Core i9",
                productIdBoxed: "BX8071512900",
                productIdTray: "BX8071512900"
            }
        },
        {
            name: "Intel Core i9-12900F",
            oem: "Intel",
            model: "Core i9-12900F",
            released: new Date("2022-01-01T05:00:00.000Z"),
            MSRP: 510,
            type: "CPU",
            img: "https://c1.neweggimages.com/ProductImageCompressAll300/19-118-373-07.jpg?ex=2",
            typeInfo: {
                platform: "desktop",
                unlocked: false,
                codename: "Alder Lake",
                architechure: "Golden Cove / Gracemont",
                PIB: "Intel Laminar RM1",
                PCIe: "5.0",
                socket: "FCLGA1700",
                memory: "DDR5 / DDR4",
                memorySpeed: "DDR5-4800 / DDR4-3200",
                memoryChannels: 2,
                cores: 16,
                pCores: 8,
                eCores: 8,
                threads: 24,
                hyperthreading: true,
                SMT: true,
                baseClock: "2.4GHz (p-core) / 1.8GHz (e-core)",
                boostClock: "5.1GHz (p-core) / 3.8GHz (e-core)",
                TjMax: "100C",
                TDP: "65W",
                L1Cache: "80KB",
                L2Cache: "14MB",
                L3Cache: "30MB",
                graphics: false,
                processNode: "Intel 7",
                productFamily: "Intel Core",
                productLine: "Intel Core i9",
                productIdBoxed: "BX8071512900F",
                productIdTray: "BX8071512900F"
            }
        },
        {
            name: "Intel Core i9-12900T",
            oem: "Intel",
            model: "Core i9-12900T",
            released: new Date("2022-02-01T05:00:00.000Z"),
            MSRP: 538,
            type: "CPU",
            img: "",
            typeInfo: {
                platform: "desktop",
                unlocked: false,
                codename: "Alder Lake",
                architechure: "Golden Cove / Gracemont",
                PIB: "Intel Laminar RM1",
                PCIe: "5.0",
                socket: "FCLGA1700",
                memory: "DDR5 / DDR4",
                memorySpeed: "DDR5-4800 / DDR4-3200",
                memoryChannels: 2,
                cores: 16,
                pCores: 8,
                eCores: 8,
                threads: 24,
                hyperthreading: true,
                SMT: true,
                baseClock: "1.4GHz (p-core) / 1.0GHz (e-core)",
                boostClock: "4.9GHz (p-core) / 3.6GHz (e-core)",
                TjMax: "100C",
                TDP: "35W",
                L1Cache: "80KB",
                L2Cache: "14MB",
                L3Cache: "30MB",
                graphics: "Intel UHD Graphics 770",
                graphincsArchitechure: "Xe",
                graphincsCores: "32",
                graphincsBaseClock: "300MHz",
                graphincsBoostClock: "1.55GHz",
                processNode: "Intel 7",
                productFamily: "Intel Core",
                productLine: "Intel Core i9",
                productIdBoxed: "BX8071512900T",
                productIdTray: "BX8071512900T"
            }
        },
        {
            name: "Intel Core i7-12700K",
            oem: "Intel",
            model: "Core i7-12700K",
            released: new Date("2021-11-04T05:00:00.000Z"),
            MSRP: 450,
            type: "CPU",
            img: "https://c1.neweggimages.com/ProductImageCompressAll300/19-118-343-05.jpg?ex=2",
            typeInfo: {
                platform: "desktop",
                unlocked: true,
                codename: "Alder Lake",
                architechure: "Golden Cove / Gracemont",
                PIB: false,
                PCIe: "5.0",
                socket: "FCLGA1700",
                memory: "DDR5 / DDR4",
                memorySpeed: "DDR5-4800 / DDR4-3200",
                memoryChannels: 2,
                cores: 12,
                pCores: 8,
                eCores: 4,
                threads: 20,
                hyperthreading: true,
                SMT: true,
                baseClock: "3.6GHz (p-core) / 2.7GHz (e-core)",
                boostClock: "5.0GHz (p-core) / 3.8GHz (e-core)",
                TjMax: "100C",
                TDP: "125W",
                L1Cache: "80KB",
                L2Cache: "12MB",
                L3Cache: "25MB",
                graphics: "Intel UHD Graphics 770",
                graphincsArchitechure: "Xe",
                graphincsCores: "32",
                graphincsBaseClock: "300MHz",
                graphincsBoostClock: "1.5GHz",
                processNode: "Intel 7",
                productFamily: "Intel Core",
                productLine: "Intel Core i7",
                productIdBoxed: "BX8071512700K",
                productIdTray: "BX8071512700K"
            }
        },
        {
            name: "Intel Core i7-12700KF",
            oem: "Intel",
            model: "Core i7-12700KF",
            released: new Date("2021-11-04T05:00:00.000Z"),
            MSRP: 422,
            type: "CPU",
            img: "https://c1.neweggimages.com/ProductImageCompressAll300/19-118-345-05.jpg?ex=2",
            typeInfo: {
                platform: "desktop",
                unlocked: true,
                codename: "Alder Lake",
                architechure: "Golden Cove / Gracemont",
                PIB: false,
                PCIe: "5.0",
                socket: "FCLGA1700",
                memory: "DDR5 / DDR4",
                memorySpeed: "DDR5-4800 / DDR4-3200",
                memoryChannels: 2,
                cores: 12,
                pCores: 8,
                eCores: 4,
                threads: 20,
                hyperthreading: true,
                SMT: true,
                baseClock: "3.6GHz (p-core) / 2.7GHz (e-core)",
                boostClock: "5.0GHz (p-core) / 3.8GHz (e-core)",
                TjMax: "100C",
                TDP: "125W",
                L1Cache: "80KB",
                L2Cache: "12MB",
                L3Cache: "25MB",
                graphics: false,
                processNode: "Intel 7",
                productFamily: "Intel Core",
                productLine: "Intel Core i7",
                productIdBoxed: "BX8071512700KF",
                productIdTray: "BX8071512700KF"
            }
        },
        {
            name: "Intel Core i7-12700",
            oem: "Intel",
            model: "Core i7-12700",
            released: new Date("2022-01-01T05:00:00.000Z"),
            MSRP: 373,
            type: "CPU",
            img: "https://c1.neweggimages.com/ProductImageCompressAll300/19-118-368-V01.jpg?ex=2",
            typeInfo: {
                platform: "desktop",
                unlocked: true,
                codename: "Alder Lake",
                architechure: "Golden Cove / Gracemont",
                PIB: false,
                PCIe: "5.0",
                socket: "FCLGA1700",
                memory: "DDR5 / DDR4",
                memorySpeed: "DDR5-4800 / DDR4-3200",
                memoryChannels: 2,
                cores: 12,
                pCores: 8,
                eCores: 4,
                threads: 20,
                hyperthreading: true,
                SMT: true,
                baseClock: "2.1GHz (p-core) / 1.6GHz (e-core)",
                boostClock: "4.9GHz (p-core) / 3.6GHz (e-core)",
                TjMax: "100C",
                TDP: "65W",
                L1Cache: "80KB",
                L2Cache: "12MB",
                L3Cache: "25MB",
                graphics: "Intel UHD Graphics 770",
                graphincsArchitechure: "Xe",
                graphincsCores: "32",
                graphincsBaseClock: "300MHz",
                graphincsBoostClock: "1.5GHz",
                processNode: "Intel 7",
                productFamily: "Intel Core",
                productLine: "Intel Core i7",
                productIdBoxed: "BX8071512700",
                productIdTray: "BX8071512700"
            }
        },
        {
            name: "Intel Core i7-12700F",
            oem: "Intel",
            model: "Core i7-12700F",
            released: new Date("2022-01-01T05:00:00.000Z"),
            MSRP: 345,
            type: "CPU",
            img: "https://c1.neweggimages.com/ProductImageCompressAll300/19-118-359-03.jpg?ex=2",
            typeInfo: {
                platform: "desktop",
                unlocked: true,
                codename: "Alder Lake",
                architechure: "Golden Cove / Gracemont",
                PIB: false,
                PCIe: "5.0",
                socket: "FCLGA1700",
                memory: "DDR5 / DDR4",
                memorySpeed: "DDR5-4800 / DDR4-3200",
                memoryChannels: 2,
                cores: 12,
                pCores: 8,
                eCores: 4,
                threads: 20,
                hyperthreading: true,
                SMT: true,
                baseClock: "2.1GHz (p-core) / 1.6GHz (e-core)",
                boostClock: "4.9GHz (p-core) / 3.6GHz (e-core)",
                TjMax: "100C",
                TDP: "65W",
                L1Cache: "80KB",
                L2Cache: "12MB",
                L3Cache: "25MB",
                graphics: false,
                processNode: "Intel 7",
                productFamily: "Intel Core",
                productLine: "Intel Core i7",
                productIdBoxed: "BX8071512700F",
                productIdTray: "BX8071512700F"
            }
        },
        {
            name: "Intel Core i7-12700T",
            oem: "Intel",
            model: "Core i7-12700T",
            released: new Date("2022-01-01T05:00:00.000Z"),
            MSRP: 373,
            type: "CPU",
            img: "",
            typeInfo: {
                platform: "desktop",
                unlocked: true,
                codename: "Alder Lake",
                architechure: "Golden Cove / Gracemont",
                PIB: false,
                PCIe: "5.0",
                socket: "FCLGA1700",
                memory: "DDR5 / DDR4",
                memorySpeed: "DDR5-4800 / DDR4-3200",
                memoryChannels: 2,
                cores: 12,
                pCores: 8,
                eCores: 4,
                threads: 20,
                hyperthreading: true,
                SMT: true,
                baseClock: "1.4GHz (p-core) / 1.0GHz (e-core)",
                boostClock: "4.7GHz (p-core) / 3.4GHz (e-core)",
                TjMax: "100C",
                TDP: "35W",
                L1Cache: "80KB",
                L2Cache: "12MB",
                L3Cache: "25MB",
                graphics: "Intel UHD Graphics 770",
                graphincsArchitechure: "Xe",
                graphincsCores: "32",
                graphincsBaseClock: "300MHz",
                graphincsBoostClock: "1.5GHz",
                processNode: "Intel 7",
                productFamily: "Intel Core",
                productLine: "Intel Core i7",
                productIdBoxed: "BX8071512700T",
                productIdTray: "BX8071512700T"
            }
        },
        {
            name: "Intel Core i5-12600K",
            oem: "Intel",
            model: "Core i5-12600K",
            released: new Date("2021-11-04T05:00:00.000Z"),
            MSRP: 318,
            type: "CPU",
            img: "https://c1.neweggimages.com/ProductImageCompressAll300/19-118-347-05.jpg?ex=2",
            typeInfo: {
                platform: "desktop",
                unlocked: true,
                codename: "Alder Lake",
                architechure: "Golden Cove / Gracemont",
                PIB: false,
                PCIe: "5.0",
                socket: "FCLGA1700",
                memory: "DDR5 / DDR4",
                memorySpeed: "DDR5-4800 / DDR4-3200",
                memoryChannels: 2,
                cores: 10,
                pCores: 6,
                eCores: 4,
                threads: 16,
                hyperthreading: true,
                SMT: true,
                baseClock: "3.7GHz (p-core) / 2.8GHz (e-core)",
                boostClock: "4.9GHz (p-core) / 3.7GHz (e-core)",
                TjMax: "100C",
                TDP: "125W",
                L1Cache: "80KB",
                L2Cache: "9.5MB",
                L3Cache: "20MB",
                graphics: "Intel UHD Graphics 770",
                graphincsArchitechure: "Xe",
                graphincsCores: "32",
                graphincsBaseClock: "300MHz",
                graphincsBoostClock: "1.45GHz",
                processNode: "Intel 7",
                productFamily: "Intel Core",
                productLine: "Intel Core i5",
                productIdBoxed: "BX8071512600K",
                productIdTray: "BX8071512600K"
            }
        },
        {
            name: "Intel Core i5-12600KF",
            oem: "Intel",
            model: "Core i5-12600KF",
            released: new Date("2021-11-04T05:00:00.000Z"),
            MSRP: 290,
            type: "CPU",
            img: "https://c1.neweggimages.com/ProductImageCompressAll300/19-118-349-05.jpg?ex=2",
            typeInfo: {
                platform: "desktop",
                unlocked: true,
                codename: "Alder Lake",
                architechure: "Golden Cove / Gracemont",
                PIB: false,
                PCIe: "5.0",
                socket: "FCLGA1700",
                memory: "DDR5 / DDR4",
                memorySpeed: "DDR5-4800 / DDR4-3200",
                memoryChannels: 2,
                cores: 10,
                pCores: 6,
                eCores: 4,
                threads: 16,
                hyperthreading: true,
                SMT: true,
                baseClock: "3.7GHz (p-core) / 2.8GHz (e-core)",
                boostClock: "4.9GHz (p-core) / 3.7GHz (e-core)",
                TjMax: "100C",
                TDP: "125W",
                L1Cache: "80KB",
                L2Cache: "9.5MB",
                L3Cache: "20MB",
                graphics: false,
                processNode: "Intel 7",
                productFamily: "Intel Core",
                productLine: "Intel Core i5",
                productIdBoxed: "BX8071512600KF",
                productIdTray: "BX8071512600KF"
            }
        },
        {
            name: "Intel Core i5-12600",
            oem: "Intel",
            model: "Core i5-12600",
            released: new Date("2022-01-01T05:00:00.000Z"),
            MSRP: 245,
            type: "CPU",
            img: "https://c1.neweggimages.com/ProductImageCompressAll300/19-118-371-S01.jpg?ex=2",
            typeInfo: {
                platform: "desktop",
                unlocked: true,
                codename: "Alder Lake",
                architechure: "Golden Cove / Gracemont",
                PIB: false,
                PCIe: "5.0",
                socket: "FCLGA1700",
                memory: "DDR5 / DDR4",
                memorySpeed: "DDR5-4800 / DDR4-3200",
                memoryChannels: 2,
                cores: 6,
                pCores: 6,
                eCores: 0,
                threads: 12,
                hyperthreading: true,
                SMT: true,
                baseClock: "3.3GHz",
                boostClock: "4.8GHz",
                TjMax: "100C",
                TDP: "65W",
                L1Cache: "80KB",
                L2Cache: "7.5MB",
                L3Cache: "18MB",
                graphics: "Intel UHD Graphics 770",
                graphincsArchitechure: "Xe",
                graphincsCores: "32",
                graphincsBaseClock: "300MHz",
                graphincsBoostClock: "1.45GHz",
                processNode: "Intel 7",
                productFamily: "Intel Core",
                productLine: "Intel Core i5",
                productIdBoxed: "BX8071512600",
                productIdTray: "BX8071512600"
            }
        },
        {
            name: "Intel Core i5-12600T",
            oem: "Intel",
            model: "Core i5-12600T",
            released: new Date("2022-01-01T05:00:00.000Z"),
            MSRP: 245,
            type: "CPU",
            img: "",
            typeInfo: {
                platform: "desktop",
                unlocked: true,
                codename: "Alder Lake",
                architechure: "Golden Cove / Gracemont",
                PIB: false,
                PCIe: "5.0",
                socket: "FCLGA1700",
                memory: "DDR5 / DDR4",
                memorySpeed: "DDR5-4800 / DDR4-3200",
                memoryChannels: 2,
                cores: 6,
                pCores: 6,
                eCores: 0,
                threads: 12,
                hyperthreading: true,
                SMT: true,
                baseClock: "2.1GHz",
                boostClock: "4.6GHz",
                TjMax: "100C",
                TDP: "35W",
                L1Cache: "80KB",
                L2Cache: "7.5MB",
                L3Cache: "18MB",
                graphics: "Intel UHD Graphics 770",
                graphincsArchitechure: "Xe",
                graphincsCores: "32",
                graphincsBaseClock: "300MHz",
                graphincsBoostClock: "1.45GHz",
                processNode: "Intel 7",
                productFamily: "Intel Core",
                productLine: "Intel Core i5",
                productIdBoxed: "BX8071512600T",
                productIdTray: "BX8071512600T"
            }
        },
        {
            name: "Intel Core i5-12500",
            oem: "Intel",
            model: "Core i5-12500",
            released: new Date("2022-01-01T05:00:00.000Z"),
            MSRP: 222,
            type: "CPU",
            img: "https://c1.neweggimages.com/ProductImageCompressAll300/19-118-374-S01.jpg?ex=2",
            typeInfo: {
                platform: "desktop",
                unlocked: true,
                codename: "Alder Lake",
                architechure: "Golden Cove / Gracemont",
                PIB: false,
                PCIe: "5.0",
                socket: "FCLGA1700",
                memory: "DDR5 / DDR4",
                memorySpeed: "DDR5-4800 / DDR4-3200",
                memoryChannels: 2,
                cores: 6,
                pCores: 6,
                eCores: 0,
                threads: 12,
                hyperthreading: true,
                SMT: true,
                baseClock: "3.0GHz",
                boostClock: "4.6GHz",
                TjMax: "100C",
                TDP: "65W",
                L1Cache: "80KB",
                L2Cache: "7.5MB",
                L3Cache: "18MB",
                graphics: "Intel UHD Graphics 770",
                graphincsArchitechure: "Xe",
                graphincsCores: "32",
                graphincsBaseClock: "300MHz",
                graphincsBoostClock: "1.45GHz",
                processNode: "Intel 7",
                productFamily: "Intel Core",
                productLine: "Intel Core i5",
                productIdBoxed: "BX8071512500",
                productIdTray: "BX8071512500"
            }
        },
        {
            name: "Intel Core i5-12500T",
            oem: "Intel",
            model: "Core i5-12500T",
            released: new Date("2022-01-01T05:00:00.000Z"),
            MSRP: 222,
            type: "CPU",
            img: "",
            typeInfo: {
                platform: "desktop",
                unlocked: true,
                codename: "Alder Lake",
                architechure: "Golden Cove / Gracemont",
                PIB: false,
                PCIe: "5.0",
                socket: "FCLGA1700",
                memory: "DDR5 / DDR4",
                memorySpeed: "DDR5-4800 / DDR4-3200",
                memoryChannels: 2,
                cores: 6,
                pCores: 6,
                eCores: 0,
                threads: 12,
                hyperthreading: true,
                SMT: true,
                baseClock: "2.0GHz",
                boostClock: "4.4GHz",
                TjMax: "100C",
                TDP: "35W",
                L1Cache: "80KB",
                L2Cache: "7.5MB",
                L3Cache: "18MB",
                graphics: "Intel UHD Graphics 770",
                graphincsArchitechure: "Xe",
                graphincsCores: "32",
                graphincsBaseClock: "300MHz",
                graphincsBoostClock: "1.45GHz",
                processNode: "Intel 7",
                productFamily: "Intel Core",
                productLine: "Intel Core i5",
                productIdBoxed: "BX8071512500T",
                productIdTray: "BX8071512500T"
            }
        },
        {
            name: "Intel Core i5-12400",
            oem: "Intel",
            model: "Core i5-12400",
            released: new Date("2022-01-01T05:00:00.000Z"),
            MSRP: 211,
            type: "CPU",
            img: "https://c1.neweggimages.com/ProductImageCompressAll300/19-118-358-S02.jpg?ex=2",
            typeInfo: {
                platform: "desktop",
                unlocked: true,
                codename: "Alder Lake",
                architechure: "Golden Cove / Gracemont",
                PIB: false,
                PCIe: "5.0",
                socket: "FCLGA1700",
                memory: "DDR5 / DDR4",
                memorySpeed: "DDR5-4800 / DDR4-3200",
                memoryChannels: 2,
                cores: 6,
                pCores: 6,
                eCores: 0,
                threads: 12,
                hyperthreading: true,
                SMT: true,
                baseClock: "2.5GHz",
                boostClock: "4.4GHz",
                TjMax: "100C",
                TDP: "65W",
                L1Cache: "80KB",
                L2Cache: "7.5MB",
                L3Cache: "18MB",
                graphics: "Intel UHD Graphics 730",
                graphincsArchitechure: "Xe",
                graphincsCores: "24",
                graphincsBaseClock: "300MHz",
                graphincsBoostClock: "1.45GHz",
                processNode: "Intel 7",
                productFamily: "Intel Core",
                productLine: "Intel Core i5",
                productIdBoxed: "BX8071512400",
                productIdTray: "BX8071512400"
            }
        },
        {
            name: "Intel Core i5-12400F",
            oem: "Intel",
            model: "Core i5-12400F",
            released: new Date("2022-01-01T05:00:00.000Z"),
            MSRP: 184,
            type: "CPU",
            img: "https://c1.neweggimages.com/ProductImageCompressAll300/19-118-360-08.jpg?ex=2",
            typeInfo: {
                platform: "desktop",
                unlocked: true,
                codename: "Alder Lake",
                architechure: "Golden Cove / Gracemont",
                PIB: false,
                PCIe: "5.0",
                socket: "FCLGA1700",
                memory: "DDR5 / DDR4",
                memorySpeed: "DDR5-4800 / DDR4-3200",
                memoryChannels: 2,
                cores: 6,
                pCores: 6,
                eCores: 0,
                threads: 12,
                hyperthreading: true,
                SMT: true,
                baseClock: "2.5GHz",
                boostClock: "4.4GHz",
                TjMax: "100C",
                TDP: "65W",
                L1Cache: "80KB",
                L2Cache: "7.5MB",
                L3Cache: "18MB",
                graphics: false,
                processNode: "Intel 7",
                productFamily: "Intel Core",
                productLine: "Intel Core i5",
                productIdBoxed: "BX8071512400F",
                productIdTray: "BX8071512400F"
            }
        },
        {
            name: "Intel Core i5-12400T",
            oem: "Intel",
            model: "Core i5-12400T",
            released: new Date("2022-01-01T05:00:00.000Z"),
            MSRP: 211,
            type: "CPU",
            img: "",
            typeInfo: {
                platform: "desktop",
                unlocked: true,
                codename: "Alder Lake",
                architechure: "Golden Cove / Gracemont",
                PIB: false,
                PCIe: "5.0",
                socket: "FCLGA1700",
                memory: "DDR5 / DDR4",
                memorySpeed: "DDR5-4800 / DDR4-3200",
                memoryChannels: 2,
                cores: 6,
                pCores: 6,
                eCores: 0,
                threads: 12,
                hyperthreading: true,
                SMT: true,
                baseClock: "2.1GHz",
                boostClock: "4.6GHz",
                TjMax: "100C",
                TDP: "35W",
                L1Cache: "80KB",
                L2Cache: "7.5MB",
                L3Cache: "18MB",
                graphics: "Intel UHD Graphics 730",
                graphincsArchitechure: "Xe",
                graphincsCores: "24",
                graphincsBaseClock: "300MHz",
                graphincsBoostClock: "1.45GHz",
                processNode: "Intel 7",
                productFamily: "Intel Core",
                productLine: "Intel Core i5",
                productIdBoxed: "BX8071512400T",
                productIdTray: "BX8071512400T"
            }
        },
        {
            name: "Intel Core i3-12300",
            oem: "Intel",
            model: "Core i3-12300",
            released: new Date("2022-01-01T05:00:00.000Z"),
            MSRP: 157,
            type: "CPU",
            img: "",
            typeInfo: {
                platform: "desktop",
                unlocked: true,
                codename: "Alder Lake",
                architechure: "Golden Cove / Gracemont",
                PIB: false,
                PCIe: "5.0",
                socket: "FCLGA1700",
                memory: "DDR5 / DDR4",
                memorySpeed: "DDR5-4800 / DDR4-3200",
                memoryChannels: 2,
                cores: 4,
                pCores: 4,
                eCores: 0,
                threads: 8,
                hyperthreading: true,
                SMT: true,
                baseClock: "3.5GHz",
                boostClock: "4.4GHz",
                TjMax: "100C",
                TDP: "60W",
                L1Cache: "80KB",
                L2Cache: "5MB",
                L3Cache: "12MB",
                graphics: "Intel UHD Graphics 730",
                graphincsArchitechure: "Xe",
                graphincsCores: "24",
                graphincsBaseClock: "300MHz",
                graphincsBoostClock: "1.45GHz",
                processNode: "Intel 7",
                productFamily: "Intel Core",
                productLine: "Intel Core i3",
                productIdBoxed: "BX8071512300",
                productIdTray: "BX8071512300"
            }
        },
        {
            name: "Intel Core i3-12300T",
            oem: "Intel",
            model: "Core i3-12300T",
            released: new Date("2022-01-01T05:00:00.000Z"),
            MSRP: 157,
            type: "CPU",
            img: "",
            typeInfo: {
                platform: "desktop",
                unlocked: true,
                codename: "Alder Lake",
                architechure: "Golden Cove / Gracemont",
                PIB: false,
                PCIe: "5.0",
                socket: "FCLGA1700",
                memory: "DDR5 / DDR4",
                memorySpeed: "DDR5-4800 / DDR4-3200",
                memoryChannels: 2,
                cores: 4,
                pCores: 4,
                eCores: 0,
                threads: 8,
                hyperthreading: true,
                SMT: true,
                baseClock: "2.3GHz",
                boostClock: "4.2GHz",
                TjMax: "100C",
                TDP: "35W",
                L1Cache: "80KB",
                L2Cache: "5MB",
                L3Cache: "12MB",
                graphics: "Intel UHD Graphics 730",
                graphincsArchitechure: "Xe",
                graphincsCores: "24",
                graphincsBaseClock: "300MHz",
                graphincsBoostClock: "1.45GHz",
                processNode: "Intel 7",
                productFamily: "Intel Core",
                productLine: "Intel Core i3",
                productIdBoxed: "BX8071512300T",
                productIdTray: "BX8071512300T"
            }
        },
        {
            name: "Intel Core i3-12100",
            oem: "Intel",
            model: "Core i3-12100",
            released: new Date("2022-01-01T05:00:00.000Z"),
            MSRP: 134,
            type: "CPU",
            img: "https://c1.neweggimages.com/ProductImageCompressAll300/A24GD2203220DB6YE7D.jpg?ex=2",
            typeInfo: {
                platform: "desktop",
                unlocked: true,
                codename: "Alder Lake",
                architechure: "Golden Cove / Gracemont",
                PIB: false,
                PCIe: "5.0",
                socket: "FCLGA1700",
                memory: "DDR5 / DDR4",
                memorySpeed: "DDR5-4800 / DDR4-3200",
                memoryChannels: 2,
                cores: 4,
                pCores: 4,
                eCores: 0,
                threads: 8,
                hyperthreading: true,
                SMT: true,
                baseClock: "3.3GHz",
                boostClock: "4.3GHz",
                TjMax: "100C",
                TDP: "60W",
                L1Cache: "80KB",
                L2Cache: "5MB",
                L3Cache: "12MB",
                graphics: "Intel UHD Graphics 730",
                graphincsArchitechure: "Xe",
                graphincsCores: "24",
                graphincsBaseClock: "300MHz",
                graphincsBoostClock: "1.4GHz",
                processNode: "Intel 7",
                productFamily: "Intel Core",
                productLine: "Intel Core i3",
                productIdBoxed: "BX8071512100",
                productIdTray: "BX8071512100"
            }
        },
        {
            name: "Intel Core i3-12100F",
            oem: "Intel",
            model: "Core i3-12100F",
            released: new Date("2022-01-01T05:00:00.000Z"),
            MSRP: 107,
            type: "CPU",
            img: "https://c1.neweggimages.com/ProductImageCompressAll300/19-118-357-03.jpg?ex=2",
            typeInfo: {
                platform: "desktop",
                unlocked: true,
                codename: "Alder Lake",
                architechure: "Golden Cove / Gracemont",
                PIB: false,
                PCIe: "5.0",
                socket: "FCLGA1700",
                memory: "DDR5 / DDR4",
                memorySpeed: "DDR5-4800 / DDR4-3200",
                memoryChannels: 2,
                cores: 4,
                pCores: 4,
                eCores: 0,
                threads: 8,
                hyperthreading: true,
                SMT: true,
                baseClock: "3.3GHz",
                boostClock: "4.3GHz",
                TjMax: "100C",
                TDP: "58W",
                L1Cache: "80KB",
                L2Cache: "5MB",
                L3Cache: "12MB",
                graphics: false,
                processNode: "Intel 7",
                productFamily: "Intel Core",
                productLine: "Intel Core i3",
                productIdBoxed: "BX8071512100F",
                productIdTray: "BX8071512100F"
            }
        },
        {
            name: "Intel Core i3-12100T",
            oem: "Intel",
            model: "Core i3-12100T",
            released: new Date("2022-01-01T05:00:00.000Z"),
            MSRP: 134,
            type: "CPU",
            img: "",
            typeInfo: {
                platform: "desktop",
                unlocked: true,
                codename: "Alder Lake",
                architechure: "Golden Cove / Gracemont",
                PIB: false,
                PCIe: "5.0",
                socket: "FCLGA1700",
                memory: "DDR5 / DDR4",
                memorySpeed: "DDR5-4800 / DDR4-3200",
                memoryChannels: 2,
                cores: 4,
                pCores: 4,
                eCores: 0,
                threads: 8,
                hyperthreading: true,
                SMT: true,
                baseClock: "2.1GHz",
                boostClock: "4.6GHz",
                TjMax: "100C",
                TDP: "35W",
                L1Cache: "80KB",
                L2Cache: "5MB",
                L3Cache: "12MB",
                graphics: "Intel UHD Graphics 730",
                graphincsArchitechure: "Xe",
                graphincsCores: "24",
                graphincsBaseClock: "300MHz",
                graphincsBoostClock: "1.45GHz",
                processNode: "Intel 7",
                productFamily: "Intel Core",
                productLine: "Intel Core i3",
                productIdBoxed: "BX8071512100T",
                productIdTray: "BX8071512100T"
            }
        },
        {
            name: "AMD Radeon RX 7900 XTX",
            oem: "AMD",
            model: "Radeon RX 7900 XTX",
            released: new Date("2022-12-13T05:00:00.000Z"),
            MSRP: 999,
            type: "GPU",
            img: "https://c1.neweggimages.com/ProductImage/14-150-875-03.jpg",
            typeInfo: {
                architechure: "RDNA3",
                cores: "96",
                memorySpeed: "GDDR6",
                vRAM: "24GB",
                L2Cache: "96MB",
                TBP: "355W",
                minPSU: "800W",
                baseClock: "1900MHz",
                gameClock: "2300MHz",
                boostClock: "2500MHz",
                h264Encode: true,
                h264Decode: true,
                h265Encode: true,
                h265Decode: true,
                av1Encode: true,
                av1Decode: true,
                HDMI: "2.1",
                DP: "2.1",
                PCIe: "4.0",
                processNode: "TSMC 5nm FinFET",
                productFamily: "AMD Radeon RX 7000-series",
                productLine: "AMD Radeon RX 7900-series"
            }
        },
        {
            name: "AMD Radeon RX 7900 XT",
            oem: "AMD",
            model: "Radeon RX 7900 XT",
            released: new Date("2022-12-13T05:00:00.000Z"),
            MSRP: 899,
            type: "GPU",
            img: "https://c1.neweggimages.com/ProductImage/14-932-588-02.jpg",
            typeInfo: {
                architechure: "RDNA3",
                cores: "84",
                memorySpeed: "GDDR6",
                vRAM: "20GB",
                L2Cache: "80MB",
                TBP: "300W",
                minPSU: "750W",
                baseClock: "1500MHz",
                gameClock: "2000MHz",
                boostClock: "2400MHz",
                h264Encode: true,
                h264Decode: true,
                h265Encode: true,
                h265Decode: true,
                av1Encode: true,
                av1Decode: true,
                HDMI: "2.1",
                DP: "2.1",
                PCIe: "4.0",
                processNode: "TSMC 5nm FinFET",
                productFamily: "AMD Radeon RX 7000-series",
                productLine: "AMD Radeon RX 7900-series"
            }
        },
        {
            name: "AMD Radeon RX 6950 XT",
            oem: "AMD",
            model: "Radeon RX 6950 XT",
            released: new Date("2022-05-10T05:00:00.000Z"),
            MSRP: 1099,
            type: "GPU",
            img: "https://c1.neweggimages.com/ProductImage/APBUS220818052S1I62.jpg",
            typeInfo: {
                architechure: "RDNA2",
                cores: "80",
                memorySpeed: "GDDR6",
                vRAM: "16GB",
                L2Cache: "128MB",
                TBP: "355W",
                minPSU: "850W",
                baseClock: "1890MHz",
                gameClock: "2100MHz",
                boostClock: "2310MHz",
                h264Encode: true,
                h264Decode: true,
                h265Encode: true,
                h265Decode: true,
                av1Encode: false,
                av1Decode: true,
                HDMI: "2.1",
                DP: "1.4a",
                processNode: "TSMC 7nm FinFET",
                productFamily: "AMD Radeon RX 5000-series",
                productLine: "AMD Radeon RX 5900-series"
            }
        },
        {
            name: "AMD Radeon RX 6900 XT",
            oem: "AMD",
            model: "Radeon RX 6900 XT",
            released: new Date("2020-12-08T05:00:00.000Z"),
            MSRP: 999,
            type: "GPU",
            img: "https://c1.neweggimages.com/ProductImage/APBUS22081804OA4F16.jpg",
            typeInfo: {
                architechure: "RDNA2",
                cores: "80",
                memorySpeed: "GDDR6",
                vRAM: "16GB",
                L2Cache: "128MB",
                TBP: "300W",
                minPSU: "850W",
                baseClock: "1890MHz",
                gameClock: "2015MHz",
                boostClock: "2250MHz",
                h264Encode: true,
                h264Decode: true,
                h265Encode: true,
                h265Decode: true,
                av1Encode: false,
                av1Decode: true,
                HDMI: "2.1",
                DP: "1.4a",
                processNode: "TSMC 7nm FinFET",
                productFamily: "AMD Radeon RX 5000-series",
                productLine: "AMD Radeon RX 5900-series"
            }
        },
        {
            name: "Intel ARC A770",
            oem: "Intel",
            model: "ARC A770",
            released: new Date("2022-10-12T05:00:00.000Z"),
            MSRP: 349,
            type: "GPU",
            img: "https://c1.neweggimages.com/ProductImageCompressAll1280/14-883-001-02.jpg",
            typeInfo: {
                architechure: "Alchemist",
                cores: "32",
                memorySpeed: "GDDR6",
                vRAM: "16GB / 8GB",
                L2Cache: "16MB",
                TBP: "225W",
                baseClock: "2100MHz",
                h264Encode: true,
                h264Decode: true,
                h265Encode: true,
                h265Decode: true,
                av1Encode: true,
                av1Decode: true,
                HDMI: "2.1",
                DP: "2.0",
                PCIe: "4.0",
                PCIeBusWidth: "x8",
                processNode: "TSMC 6nm FinFET",
                productFamily: "Intel Xe ARC HPG",
                productLine: "Intel Xe ARC HPG A-series"
            }
        },
        {
            name: "Intel ARC A750",
            oem: "Intel",
            model: "ARC A750",
            released: new Date("2022-10-12T05:00:00.000Z"),
            MSRP: 289,
            type: "GPU",
            img: "https://c1.neweggimages.com/ProductImageCompressAll1280/14-883-002-02.jpg",
            typeInfo: {
                architechure: "Alchemist",
                cores: "28",
                memorySpeed: "GDDR6",
                vRAM: "8GB",
                L2Cache: "12MB",
                TBP: "175W",
                baseClock: "2050MHz",
                h264Encode: true,
                h264Decode: true,
                h265Encode: true,
                h265Decode: true,
                av1Encode: true,
                av1Decode: true,
                HDMI: "2.1",
                DP: "2.0",
                PCIe: "4.0",
                processNode: "TSMC 6nm FinFET",
                productFamily: "Intel Xe ARC HPG",
                productLine: "Intel Xe ARC HPG A-series"
            }
        },
        {
            name: "Intel ARC A380",
            oem: "Intel",
            model: "ARC A380",
            released: new Date("2022-06-14T05:00:00.000Z"),
            MSRP: 139,
            type: "GPU",
            img: "https://c1.neweggimages.com/ProductImageCompressAll1280/14-930-076-05.jpg",
            typeInfo: {
                architechure: "Alchemist",
                cores: "8",
                memorySpeed: "GDDR6",
                vRAM: "6GB",
                L2Cache: "4MB",
                TBP: "75W",
                baseClock: "2000MHz",
                h264Encode: true,
                h264Decode: true,
                h265Encode: true,
                h265Decode: true,
                av1Encode: true,
                av1Decode: true,
                HDMI: "2.1",
                DP: "2.0",
                PCIe: "4.0",
                processNode: "TSMC 6nm FinFET",
                productFamily: "Intel Xe ARC HPG",
                productLine: "Intel Xe ARC HPG A-series"
            }
        },
        {
            name: "NVIDIA GeForce RTX 4090",
            oem: "NVIDIA",
            model: "NVIDIA GeForce RTX 4090",
            released: new Date("2022-10-12T05:00:00.000Z"),
            MSRP: 1599,
            type: "GPU",
            img: "https://assets.nvidia.partners/images/png/GeForce-RTX4090-Back.png",
            typeInfo: {
                architechure: "Ada Lovelace AD102-300",
                codename: "Ada Lovelace",
                cores: "16384",
                memorySpeed: "GDDR6X",
                vRAM: "24GB",
                L2Cache: "72MB",
                TBP: "450W",
                minPSU: "850W",
                baseClock: "2230MHz",
                boostClock: "2520MHz",
                h264Encode: true,
                h264Decode: true,
                h265Encode: true,
                h265Decode: true,
                av1Encode: true,
                av1Decode: true,
                TjMax: "90C",
                PCIe: "4.0",
                HDMI: "2.1",
                DP: "1.4a",
                processNode: "TSMC 4nm FinFET",
                productFamily: "NVIDIA GeForce RTX",
                productLine: "NVIDIA GeForce RTX 4000-series"
            }
        },
        {
            name: "NVIDIA GeForce RTX 4080",
            oem: "NVIDIA",
            model: "NVIDIA GeForce RTX 4080",
            released: new Date("2022-10-12T05:00:00.000Z"),
            MSRP: 1199,
            type: "GPU",
            img: "https://assets.nvidia.partners/images/png/GeForce-RTX4080-Back.png",
            typeInfo: {
                architechure: "Ada Lovelace AD103-300",
                codename: "Ada Lovelace",
                cores: "9728",
                memorySpeed: "GDDR6X",
                vRAM: "16GB",
                L2Cache: "64MB",
                TBP: "320W",
                minPSU: "750W",
                baseClock: "2210MHz",
                boostClock: "2510MHz",
                h264Encode: true,
                h264Decode: true,
                h265Encode: true,
                h265Decode: true,
                av1Encode: true,
                av1Decode: true,
                TjMax: "90C",
                PCIe: "4.0",
                HDMI: "2.1",
                DP: "1.4a",
                processNode: "TSMC 4nm FinFET",
                productFamily: "NVIDIA GeForce RTX",
                productLine: "NVIDIA GeForce RTX 4000-series"
            }
        }
    ];
    for (const part of parts) {
        await part_1.default.updateOne({
            $or: Object.entries(part)
                .filter(([prop]) => ["_id", "name", "model"].includes(prop))
                .map(([p, v]) => ({ [p]: v }))
        }, part, { upsert: true });
    }
    console.log(`\n\t> MongoDB: "${MONGODB}" initialized.\n`);
    process.exit(0);
})();
//# sourceMappingURL=docker-init-db.js.map